spring:
  kafka:
    bootstrap-servers: localhost:9092

minio:
  endpoint: http://localhost:9000
  access-key: minadmin
  secret-key: minadmin

# Wiki Dump 수집 설정
wiki:
  dump:
    storage:
      path: ./wiki-dumps
    processing:
      batch-size: 1000

logging:
  level:
    com.realtime.collectionsystem: INFO
    org.springframework.kafka: INFO
    org.apache.kafka.clients.producer.ProducerConfig: WARN
    org.apache.kafka.clients: WARN
    org.jsoup: WARN
    com.rometools: WARN
    root: INFO