server:
  port: 8083

spring:
  application:
    name: indexing-system
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: indexing-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 10s
    socket-timeout: 60s

logging:
  level:
    com.yjham.realtime.indexing: DEBUG
    org.springframework.data.elasticsearch: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics